# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=56, verbose_name='资源标题')),
                ('url', models.URLField(verbose_name='资源链接')),
                ('password', models.CharField(default='0000', max_length=24, verbose_name='链接密码')),
                ('abstract', models.TextField(verbose_name='资源简介')),
                ('images', models.ImageField(upload_to='study/images/', verbose_name='资源图片')),
            ],
            options={
                'verbose_name_plural': '资源',
                'ordering': ['-create_time'],
                'verbose_name': '资源',
            },
        ),
    ]
