# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 09:26
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type_id', models.SmallIntegerField(choices=[(1, 'python'), (2, '前端html和css'), (3, 'javascript'), (4, 'mysql'), (5, 'mongodb'), (6, 'redis'), (7, '爬虫'), (8, 'django'), (9, 'tornado'), (10, 'linux'), (11, 'go'), (12, '闲谈')], default=1, verbose_name='id')),
                ('type', models.CharField(default='python', max_length=50, verbose_name='文章类型')),
                ('title', models.CharField(max_length=40, verbose_name='博文标题')),
                ('author', models.CharField(default='漂泊在北京', max_length=20, verbose_name='博文作者')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('date', models.DateField(verbose_name='发布时间')),
                ('images', models.ImageField(upload_to='images', verbose_name='博文图片')),
                ('description', models.TextField(verbose_name='博文简介')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='博文内容')),
            ],
            options={
                'verbose_name': '博客',
                'ordering': ['create_time'],
                'verbose_name_plural': '博客',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categor', models.CharField(max_length=40, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'ordering': ['-id'],
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='评论人昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='评论人邮件')),
                ('url', models.CharField(max_length=256, verbose_name='网址')),
                ('comment', models.TextField(verbose_name='评论内容')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Article', verbose_name='博客')),
            ],
            options={
                'verbose_name': '评论',
                'ordering': ['create_time'],
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱',
                'verbose_name_plural': '邮箱',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
                ('callback_url', models.URLField(verbose_name='url')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'ordering': ['-id'],
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮件')),
                ('url', models.CharField(max_length=256, verbose_name='网址')),
                ('comment', models.TextField(verbose_name='内容')),
                ('number', models.PositiveIntegerField(default=0, verbose_name='留言数')),
            ],
            options={
                'verbose_name': '留言板',
                'ordering': ['create_time'],
                'verbose_name_plural': '留言板',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Category', verbose_name='标签'),
        ),
    ]
