# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(default='python', max_length=40, verbose_name='博文类型'),
        ),
    ]
