# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ImageField(upload_to='images/', verbose_name='博文图片'),
        ),
    ]
