# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-23 10:27
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', max_length=102400000000000000, verbose_name='博文内容'),
        ),
    ]
