# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180119_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type_id',
            field=models.SmallIntegerField(choices=[(1, 'python'), (2, '前端html和css'), (3, 'javascript'), (4, 'mysql'), (5, 'redis'), (6, '爬虫'), (7, 'django'), (8, 'tornado'), (9, 'linux'), (10, 'go'), (11, '闲谈')], default=1, verbose_name='id'),
        ),
    ]
