# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=50, verbose_name='博客标题')),
                ('url', models.URLField(verbose_name='博客链接')),
                ('images', models.ImageField(upload_to='images/message/', verbose_name='博客图片')),
                ('abstract', models.TextField(verbose_name='博客简介')),
            ],
            options={
                'verbose_name_plural': '博客收录',
                'ordering': ['-create_time'],
                'verbose_name': '博客收录',
            },
        ),
        migrations.CreateModel(
            name='FreshNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=256, verbose_name='新闻标题')),
                ('url', models.URLField(verbose_name='新闻链接')),
                ('views', models.CharField(max_length=12, verbose_name='新鲜度')),
                ('category', models.CharField(max_length=24, verbose_name='来源')),
            ],
            options={
                'verbose_name_plural': '新鲜事',
                'ordering': ['-views'],
                'verbose_name': '新鲜事',
            },
        ),
    ]
