# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-15 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=56, verbose_name='电影标题')),
                ('url', models.URLField(verbose_name='电影链接')),
                ('rate', models.CharField(max_length=10, verbose_name='电影评分')),
                ('images', models.ImageField(upload_to='movies/images/', verbose_name='电影图片')),
                ('abstract', models.TextField(verbose_name='电影简介')),
            ],
            options={
                'ordering': ['-rate'],
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='WatchMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=50, verbose_name='网站名')),
                ('url', models.URLField(verbose_name='网站地址')),
                ('abstract', models.TextField(verbose_name='网站简介')),
                ('images', models.ImageField(upload_to='movies/website_images/', verbose_name='网站图片')),
            ],
            options={
                'ordering': ['-create_time'],
                'verbose_name': '观影小站',
                'verbose_name_plural': '观影小站',
            },
        ),
    ]
